version: "3.7"

services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - "3000:80"
    volumes:
      - "./src/:/var/www"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - "9000:9000"
    volumes:
      - "./src/:/var/www"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
