version: "3.7"

services:
  nginx:
    image: nginx:1.11.10
    ports:
      - "3000:80"
    volumes:
      - "./src/:/var/www"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      DB_NAME: app
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: db
    expose:
      - "9000:9000"
    volumes:
      - "./src/:/var/www"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
